

services:
  nginx:
    image: nginx:latest
    container_name: lemp_nginx
    ports:
      - "8081:80"  # Expose container's Nginx on port 8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: lemp_php
    volumes:
      - ./html:/var/www/html

